-- CREATE TABLE `skills` (
--   `id` bigint(20) NOT NULL AUTO_INCREMENT,
--   `sname` varchar(255) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE skills (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sname VARCHAR(250) NOT NULL
);
